package com.example.demo.transport;

import lombok.Data;
import lombok.ToString;

/**
 * Created by user on 14.10.2018.
 */
@Data
@ToString
public class StackOverFlowSurvey {

    private String column;
    private String respondent;
    private String hobby;
    private String openSource;
    private String country;
    private String student;
    private String employment;
    private String formalEducation;
    private String undergradMajor;
    private String companySize;
    private String devType;
    private String yearsCoding;
    private String yearsCodingProf;
    private String jobSatisfaction;
    private String careerSatisfaction;
    private String hopeFiveYears;
    private String jobSearchStatus;
    private String lastNewJob;
    private String assessJob1;
    private String assessJob2;
    private String assessJob3;
    private String assessJob4;
    private String assessJob5;
    private String assessJob6;
    private String assessJob7;
    private String assessJob8;
    private String assessJob9;
    private String assessJob10;
    private String assessBenefits1;
    private String assessBenefits2;
    private String assessBenefits3;
    private String assessBenefits4;
    private String assessBenefits5;
    private String assessBenefits6;
    private String assessBenefits7;
    private String assessBenefits8;
    private String assessBenefits9;
    private String assessBenefits10;
    private String assessBenefits11;
    private String jobContactPriorities1;
    private String jobContactPriorities2;
    private String jobContactPriorities3;
    private String jobContactPriorities4;
    private String jobContactPriorities5;
    private String jobEmailPriorities1;
    private String jobEmailPriorities2;
    private String jobEmailPriorities3;
    private String jobEmailPriorities4;
    private String jobEmailPriorities5;
    private String jobEmailPriorities6;
    private String jobEmailPriorities7;
    private String updateCV;
    private String currency;
    private String salary;
    private String salaryType;
    private String convertedSalary;
    private String currencySymbol;
    private String communicationTools;
    private String timeFullyProductive;
    private String educationTypes;
    private String selfTaughtTypes;
    private String timeAfterBootcamp;
    private String hackathonReasons;
    private String agreeDisagree1;
    private String agreeDisagree2;
    private String agreeDisagree3;
    private String languageWorkedWith;
    private String languageDesireNextYear;
    private String databaseWorkedWith;
    private String databaseDesireNextYear;
    private String platformWorkedWith;
    private String platformDesireNextYear;
    private String frameworkWorkedWith;
    private String frameworkDesireNextYear;
    private String iDE;
    private String operatingSystem;
    private String numberMonitors;
    private String methodology;
    private String versionControl;
    private String checkInCode;
    private String adBlocker;
    private String adBlockerDisable;
    private String adBlockerReasons;
    private String adsAgreeDisagree1;
    private String adsAgreeDisagree2;
    private String adsAgreeDisagree3;
    private String adsActions;
    private String adsPriorities1;
    private String adsPriorities2;
    private String adsPriorities3;
    private String adsPriorities4;
    private String adsPriorities5;
    private String adsPriorities6;
    private String adsPriorities7;
    private String aIDangerous;
    private String aIInteresting;
    private String aIResponsible;
    private String aIFuture;
    private String ethicsChoice;
    private String ethicsReport;
    private String ethicsResponsible;
    private String ethicalImplications;
    private String stackOverflowRecommend;
    private String stackOverflowVisit;
    private String stackOverflowHasAccount;
    private String stackOverflowParticipate;
    private String stackOverflowJobs;
    private String stackOverflowDevStory;
    private String stackOverflowJobsRecommend;
    private String stackOverflowConsiderMember;
    private String hypotheticalTools1;
    private String hypotheticalTools2;
    private String hypotheticalTools3;
    private String hypotheticalTools4;
    private String hypotheticalTools5;
    private String wakeTime;
    private String hoursComputer;
    private String hoursOutside;
    private String skipMeals;
    private String ergonomicDevices;
    private String exercise;
    private String gender;
    private String sexualOrientation;
    private String educationParents;
    private String raceEthnicity;
    private String age;
    private String dependents;
    private String militaryUS;
    private String surveyTooLong;
    private String surveyEasy;

}
